LOCAL_C_INCLUDES := $(LOCAL_PATH) \
$(LOCAL_PATH)/../src/main/ \
$(LOCAL_PATH)/../src/main//res \
$(LOCAL_PATH)/../src/main//res/mipmap-mdpi \
$(LOCAL_PATH)/../src/main//res/drawable-v24 \
$(LOCAL_PATH)/../src/main//res/mipmap-hdpi \
$(LOCAL_PATH)/../src/main//res/drawable \
$(LOCAL_PATH)/../src/main//res/mipmap-xxxhdpi \
$(LOCAL_PATH)/../src/main//res/layout \
$(LOCAL_PATH)/../src/main//res/mipmap-xxhdpi \
$(LOCAL_PATH)/../src/main//res/values \
$(LOCAL_PATH)/../src/main//res/navigation \
$(LOCAL_PATH)/../src/main//res/xml \
$(LOCAL_PATH)/../src/main//res/drawable-v21 \
$(LOCAL_PATH)/../src/main//res/menu \
$(LOCAL_PATH)/../src/main//res/mipmap-xhdpi \
$(LOCAL_PATH)/../src/main//res/mipmap-anydpi-v26 \
$(LOCAL_PATH)/../src/main//java \
$(LOCAL_PATH)/../src/main//java/com \
$(LOCAL_PATH)/../src/main//java/com/im30 \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ads \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui/home \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui/gallery \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui/activitys \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui/slideshow \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/ui/login \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/thirdSDK \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/utils \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/data \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/data/model \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/pushdemo \
$(LOCAL_PATH)/../src/main//java/com/im30/googledemo/media \
$(LOCAL_PATH)/../src/main//cpp \

